"""added passion column

Revision ID: bb08e4fb9dad
Revises: 
Create Date: 2020-06-04 17:33:06.596690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb08e4fb9dad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pradip', sa.Column('passion', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pradip', 'passion')
    # ### end Alembic commands ###
