"""model created

Revision ID: 6b9eabcd4365
Revises: a45f19ab0958
Create Date: 2020-06-04 22:19:41.816282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b9eabcd4365'
down_revision = 'a45f19ab0958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puppies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.Text(), nullable=True),
    sa.Column('puppy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['puppy_id'], ['puppies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('passion')
    op.drop_table('pradip')
    op.add_column('owners', sa.Column('puppy_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'owners', type_='foreignkey')
    op.create_foreign_key(None, 'owners', 'puppies', ['puppy_id'], ['id'])
    op.drop_column('owners', 'passion_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owners', sa.Column('passion_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'owners', type_='foreignkey')
    op.create_foreign_key(None, 'owners', 'pradip', ['passion_id'], ['id'])
    op.drop_column('owners', 'puppy_id')
    op.create_table('pradip',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passion',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('item_name', sa.TEXT(), nullable=True),
    sa.Column('passion_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['passion_id'], ['pradip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('toys')
    op.drop_table('puppies')
    # ### end Alembic commands ###
