"""model created

Revision ID: a45f19ab0958
Revises: 
Create Date: 2020-06-04 18:50:33.867009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a45f19ab0958'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pradip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('passion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['passion_id'], ['pradip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.Text(), nullable=True),
    sa.Column('passion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['passion_id'], ['pradip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passion')
    op.drop_table('owners')
    op.drop_table('pradip')
    # ### end Alembic commands ###
